# Generated by Django 4.0.3 on 2022-04-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user_since_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('medical_license', models.CharField(max_length=100)),
                ('doc_speciality', models.CharField(max_length=200)),
                ('doc_score', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='med_post',
            fields=[
                ('med_post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('med_post_datetime', models.DateTimeField(auto_now_add=True)),
                ('med_post_text', models.TextField()),
                ('med_post_likes', models.BigIntegerField()),
                ('med_post_doc_likes', models.BigIntegerField()),
                ('med_post_score', models.BigIntegerField()),
                ('med_post_commented', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_datetime', models.DateTimeField(auto_now_add=True)),
                ('med_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.med_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('med_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.med_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
