# Generated by Django 4.0.3 on 2022-04-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_first_name_alter_user_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_post',
            name='med_post_commented',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
